<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>FloorCreator</AssemblyName>
	<RootNamespace>FloorCreator</RootNamespace>
	<BaseOutputPath></BaseOutputPath>
	<DefaultItemExcludes>$(DefaultItemExcludes);FloorCreator\**;FloorCreator25\**</DefaultItemExcludes>
  </PropertyGroup>
	<ItemGroup>
		<Resource Include="Resources\citrus.ico" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="CitrusTheme\" />
	</ItemGroup>
</Project>
